server:
  port: 8280
#Logback Config
logging:
  config: classpath:config/logback/logback-spring.xml
  path: logs
  level:
    com.wre.game.api.dao: debug

backend:
  api:
    token:
      secret: cRlreScAI25hZ2ILbMa=
      #JWT Token Key - expire 360days
      expire:
        millis: 31104000000
      # redis expire 30 days
      redis:
        expire:
          second: 2592000
config:
  game: /data/bin/game-config.json
  ip: /data/bin/ip-config.json
  product-list: /data/bin/product-list.json

spring:
  datasource:
    url: jdbc:mysql://database-1.c0ukmufjemvj.ap-northeast-1.rds.amazonaws.com:3306/wre_game?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 'fa09hoano()ldade#'
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 10
    minIdle: 10
    maxActive: 200
    # 配置获取连接等待超时的时间
    maxWait: 10000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  redis:
    host: hospitap-jp.6crsms.ng.0001.apne1.cache.amazonaws.com
    port: 6379
    database: 0
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    #password:
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait: 1000ms
        # 最大活跃连接数，负数为不限制
        max-active: -1
    password:

  jackson:
    default-property-inclusion: non_null


mybatis:
  typeAliasesPackage: com.wre.game.api.data.entity
  mapper-locations: classpath:mapper/*.xml


payment:
  #0 sandbox, 1 product
  iosType: 1

recharge:
  port: 10080

