
#端口号
server:
   port: 8082
#2.0版本的Spring配置path方式
#   servlet:
#     context-path: /GameServer
logging:
#Logback Config
   config: ./config/logback/logback-spring.xml
   level:
      com.wre.game.api.dao: debug
backend:
   api:
      token:
         secret: cRlreScAI25hZ2ILbMa=
         expire:
            millis: 864000000
#JWT Token Key - expire 7days
         redis:
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录
            expire:
               second: 864000
config:
   game: ./config/game-config.json
   ip: ./config/ip-config.json
   product-list: ./config/product-list.json

spring:
   jackson:
      date-fomat: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/wre_game?useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      ###################以下为druid增加的配置###########################
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 10
      maxActive: 300
      # 配置获取连接等待超时的时间
      maxWait: 10000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 10000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 120000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
      filters:
         commons-log.connection-logger-name: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

   redis:
      host: 127.0.0.1
# 合并多个DruidDataSource的监控数据
      port: 6379
      database: 0
      timeout: 60s # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
      password:
      jedis:
         pool:
            max-idle: 500
            min-idle: 50
# 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
            max-wait: 1000ms
            max-active: -1
# 最大空闲连接数

# 最小空闲连接数
      default-property-inclusion: non_null
# 等待可用连接的最大时间，负数为不限制
mybatis:
# 最大活跃连接数，负数为不限制
   typeAliasesPackage: com.wre.game.api.data.entity
   mapper-locations: classpath:mapper/*.xml
payment:
   iosType: 0

recharge:
   port: 10080
